"""empty message

Revision ID: 448292cfd149
Revises: d9f136f84e13
Create Date: 2023-12-29 22:21:41.263677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448292cfd149'
down_revision = 'd9f136f84e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
